### ISSUE TITLE
Why are there no identified results?

### ISSUE THREAD

**Issue by yhz5256** [jiaoml1996/ScenceRecognition#4]
start to recognize : imgs/002.jpg
Detection took 0.903s for 1000 object proposals
---------------------------------------------------------------
start to recognize : imgs/test1.png
Detection took 0.194s for 82 object proposals
yang@yang-System-Product-Name:/media/yang/KINGSTON$

**Comment by jiaoml1996** [comment]
> ## start to recognize : imgs/002.jpg
> Detection took 0.903s for 1000 object proposals
> start to recognize : imgs/test1.png
> Detection took 0.194s for 82 object proposals
> yang@yang-System-Product-Name:/media/yang/KINGSTON$

you can get the result from the 35,36 lines in "demo.py".
you can modify the code
 `plt.imshow(img)
  plt.show()`

**Comment by yhz5256** [comment]
> > ## start to recognize : imgs/002.jpg
> > Detection took 0.903s for 1000 object proposals
> > start to recognize : imgs/test1.png
> > Detection took 0.194s for 82 object proposals
> > yang@yang-System-Product-Name:/media/yang/KINGSTON$
> 
> you can get the result from the 35,36 lines in "demo.py".
> you can modify the code
> `plt.imshow(img) plt.show()`

I want to output the result of the recognition, but why not?
