### ISSUE TITLE
How can I get a picture like the following？Or is there any way to output this image?

### ISSUE THREAD

**Issue by JianqingWeng** [jiaoml1996/ScenceRecognition#6]
![image](https://user-images.githubusercontent.com/25848511/53289228-6e9bb680-37ce-11e9-938d-4fc604d06694.png)

**Comment by jiaoml1996** [comment]
you can look at the demo.py

**Comment by JianqingWeng** [comment]
> you can look at the demo.py
Ok.Thank！
