### ISSUE TITLE
Could you have another link to download demo model file ?

### ISSUE THREAD

**Issue by HuyQLuong** [jiaoml1996/ScenceRecognition#9]
As what I was writing in the title, could you provide another link easier to download ? Thank you very much and really appreciate your work !

**Comment by jiaoml1996** [comment]
> As what I was writing in the title, could you provide another link easier to download ? Thank you very much and really appreciate your work !

Please provide your email address. I will send it to you by email.

**Comment by HuyQLuong** [comment]
Thanks, I have send you an email

**Comment by jiaoml1996** [comment]
> Thanks, I have send you an email

Ok, please check your email.
